spring:
  config:
    activate:
      on-profile: test

jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false

kartoush:
  email:
    delivery:
      provider: ${KARTOUSH_EMAIL_DELIVERY_PROVIDER:noop}
      enabled: ${KARTOUSH_EMAIL_DELIVERY_ENABLED:false}
