spring:
  config:
    activate:
      on-profile: prod

kartoush:
  email:
    delivery:
      provider: ${KARTOUSH_EMAIL_DELIVERY_PROVIDER:brevo}
      enabled: ${KARTOUSH_EMAIL_DELIVERY_ENABLED:true}
      brevo:
        api-base-url: ${KARTOUSH_EMAIL_BREVO_API_BASE_URL:https://api.brevo.com/v3}
        api-key: ${KARTOUSH_EMAIL_BREVO_API_KEY:}
