spring:
  config:
    activate:
      on-profile: dev

jobrunr:
  background-job-server:
    enabled: ${KARTOUSH_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED:true}
  dashboard:
    enabled: ${KARTOUSH_JOBRUNR_DASHBOARD_ENABLED:true}
    port: ${KARTOUSH_JOBRUNR_DASHBOARD_PORT:8000}

kartoush:
  jobs:
    cleanup:
      enabled: true
  email:
    customer:
      activation-base-url: ${KARTOUSH_EMAIL_ACTIVATION_BASE_URL:http://localhost:8080/dev/customers/activate}
      password-reset-base-url: ${KARTOUSH_EMAIL_PASSWORD_RESET_BASE_URL:http://localhost:8080/dev/auth/password-reset}
    delivery:
      provider: ${KARTOUSH_EMAIL_DELIVERY_PROVIDER:mailtrap}
      enabled: ${KARTOUSH_EMAIL_DELIVERY_ENABLED:false}
      mailtrap:
        api-token: ${KARTOUSH_EMAIL_MAILTRAP_API_TOKEN:}
        inbox-id: ${KARTOUSH_EMAIL_MAILTRAP_INBOX_ID:0}
