spring:
  config:
    activate:
      on-profile: prod

jobrunr:
  background-job-server:
    enabled: ${KARTOUSH_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED:true}
  dashboard:
    enabled: ${KARTOUSH_JOBRUNR_DASHBOARD_ENABLED:false}

kartoush:
  jobs:
    activation-email:
      encryption-key: ${KARTOUSH_JOBS_ACTIVATION_EMAIL_ENCRYPTION_KEY:}
  email:
    delivery:
      provider: ${KARTOUSH_EMAIL_DELIVERY_PROVIDER:brevo}
      enabled: ${KARTOUSH_EMAIL_DELIVERY_ENABLED:true}
      brevo:
        api-base-url: ${KARTOUSH_EMAIL_BREVO_API_BASE_URL:https://api.brevo.com/v3}
        api-key: ${KARTOUSH_EMAIL_BREVO_API_KEY:}
